fresh_shop/cart/urls.py
"""__author__=wuliang"""
from django.conf.urls import url

from cart import views

urlpatterns = [
	url(r'^addcart/', views.addcart, name='addcart'),
	url(r'^show_cart/', views.show_cart, name='show_cart'),

	url(r'^delcart/', views.delcart, name='delcart'),
]

fresh_shop/fresh_shop/urls.py
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import static
from django.contrib import admin

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^user/', include('user.urls', namespace='user')),
	url(r'^goods/', include('goods.urls', namespace='goods')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^order/', include('order.urls', namespace='order'))
]

urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
"""__author__=wuliang"""

from django.conf.urls import url

from goods import views

urlpatterns = [
	url(r'^index/', views.index, name='index'),
	url(r'^detail/(\d+)', views.detail, name='detail'),
	url(r'^show_list/', views.show_list, name='show_list'),
]

fresh_shop/order/urls.py
"""__author__=wuliang"""

from django.conf.urls import  url

from order import views

urlpatterns = [
	url(r'^place_order/', views.place_order, name='place_order'),
	url(r'^add_order/', views.add_order, name='add_order'),
]

fresh_shop/user/urls.py
"""__author__=wuliang"""
from django.conf.urls import url

from user import views

urlpatterns = [
	url(r'^login/', views.login, name='login'),
	url(r'^logout/', views.logout, name='logout'),
	url(r'^register/', views.register, name='register'),
	url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
	url(r'^user_center_site/', views.user_center_site, name='user_center_site'),

	url(r'^user_center_order/', views.user_center_order, name='user_center_order'),

]

fresh_shop/cart/models.py
from django.db import models

# Create your models here.
from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
	"""
	购物车
	"""
	user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
	goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
	nums = models.IntegerField(default=0, verbose_name='数量')
	add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
	is_select = models.BooleanField(default=True)

	class Meta:
		db_table = 'f_shopping_cart'

fresh_shop/user/models.py
from django.db import models

# Create your models here.
from goods.models import Goods


class User(models.Model):
	"""
	    用户表
	"""
	username = models.CharField(max_length=20, unique=True, null=True, blank=True, verbose_name="姓名")
	password = models.CharField(max_length=255, verbose_name="密码")
	birthday = models.DateField(null=True, blank=True, verbose_name="出生年月")
	GENDER = (
	    ("male", u"男"),
	    ("female", "女")
	)
	gender = models.CharField(max_length=6, choices=GENDER, default="female",
	                              verbose_name="性别")
	mobile = models.CharField(null=True, blank=True, max_length=11, verbose_name="电话")
	email = models.EmailField(max_length=100, null=True, blank=True, verbose_name="邮箱")

	class Meta:
		db_table = 'f_user'


class UserAddress(models.Model):
	"""
	收货地址表
	"""
	user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
	province = models.CharField(max_length=100, default='', verbose_name='省份')
	city = models.CharField(max_length=100, default='', verbose_name='城市')
	district = models.CharField(max_length=100, default='', verbose_name='区域')
	address = models.CharField(max_length=100, default='', verbose_name='详细地址')
	signer_name = models.CharField(max_length=20, default='', verbose_name='签收人')
	signer_mobile = models.CharField(max_length=11, default='', verbose_name='电话')
	signer_postcode = models.CharField(max_length=11, default='', verbose_name='邮编')
	add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

	class Meta:
		db_table = 'f_user_address'

fresh_shop/cart/views.py
import random
import time

from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from cart.models import ShoppingCart
from goods.models import Goods
from utils.functions import add_cart_no_login


@add_cart_no_login
def addcart(request):
	if request.method == 'GET':
		# 加入到购物车，需判断用户是否登录
		# 如果登录，加入到购物车中的数据，其实是加入到数据库中购物车表里
		# 如果没有登录，则加入到购物车中的数据，是加入到session中


		# 如果登录，则加入到购物车中的数据，是加入到session中
		# session中存储数据：商品id,商品数量，商品选择状态
		# 如果登录，则把session中的数据同步到数据库中(中间件同步数据)
		goods_list = request.session.get('goods_list')
		cart_list = []
		s = '1234abcd'
		if goods_list:
			for goods_dict in goods_list:
				cart_dict = {}

				for key, value in goods_dict.items():
					id = ''
					# 获取session所有商品信息
					goods = Goods.objects.filter(pk=key).first()
					cart_dict['goods'] = goods
					cart_dict['nums'] = value
					for _ in range(4):
						id = random.choice(s)
					cart_dict['id'] = id

				cart_list.append(cart_dict)
			num = len(cart_list)

			return render(request,'cart.html',{'cart_list':cart_list,'len':num})

		else:
			user_id = request.session.get ('user_id')
			if user_id:
				return HttpResponseRedirect(reverse('cart:show_cart'))
			else:
				return render(request,'cart.html')

	if request.method == 'POST':
		goods_list = request.session.get ('goods_list')
		if goods_list:
			num = len(goods_list)
		else:
			user = request.user
			if user:
				num = ShoppingCart.objects.filter(user=user).count()
		return JsonResponse({'code':200,'msg':'添加成功','len':num})


def show_cart(request):
	if request.method == 'GET':
		user_id = request.session.get('user_id')
		if not user_id:
			return HttpResponseRedirect(reverse('cart:addcart'))
		else:
			cart = ShoppingCart.objects.filter(user=request.user)
			len = cart.all().count()

			return render(request, 'cart.html',{'cart_list': cart,'len': len})

def delcart(request):
	if request.method == 'POST':
		id = request.POST.get('goods_id')
		user_id = request.session.get('user_id')
		if not user_id:
			# 没登录
			goods_list = request.session.get('goods_list')
			for goods_dict in goods_list:
				for key in goods_dict:
					if key == id:
						goods_list.remove(goods_dict)
			request.session['goods_list'] = goods_list

		else:
			goods = Goods.objects.filter(pk=id).first()
			ShoppingCart.objects.filter(user=request.user, goods=goods).delete()

		return JsonResponse({'code':200, 'msg':'删除成功'})

fresh_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>

        {% block title %}

        {% endblock %}
    </title>

    {% block css %}

    {% endblock %}


    {% block js %}

    {% endblock %}
</head>

<body>
 {% block header_con %}
    {% endblock %}

    {% block search_bar %}
    {% endblock %}

    {% block content %}

    {% endblock %}


    {% block footer %}
    {% endblock %}

    {% block bot_js %}

    {% endblock %}
</body>
</html>

fresh_shop/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}


{% block header_con %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.id %}
				<div class="login_info fl" style="display: block">
					欢迎您：<em>{{ user.username }}</em>&nbsp;|&nbsp;
                    <a style="color: gray" href="{% url 'user:logout' %}">注销</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show_cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}


{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:addcart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ len }}</div>
		</div>
	</div>
{% endblock %}


{% block footer %}
    	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-首页
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>

{% endblock %}

{% block content %}
    	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

        {% for type in types %}

	<div class="list_model">
		<div class="list_title clearfix">


			<h3 class="fl" id="model0{{ type.0 }}">{{ type.1 }}</h3>

			<div class="subtitle fl">
				<span>|</span>
                 {% for category in categorys %}
                     {% if type.0 == category.id %}
                         {% for goods in category.goods_set.all %}
                             {% if forloop.counter <= 4 %}
				                <a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a>
                             {% endif %}
                         {% endfor %}
                     {% endif %}
                 {% endfor %}
			</div>
			<a href="{% url 'goods:show_list' %}?type={{ type.0 }}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
            {% for category in categorys %}
                {% ifequal category.id type.0 %}
			<div class="goods_banner fl"><img src="/media/{{ category.category_front_image }}"></div>
                {% endifequal %}
            {% endfor %}
            <ul class="goods_list fl">
            {% for category in categorys %}
                {% if category.id == type.0 %}
                        {% for goods in category.goods_set.all %}
                            {% if forloop.counter <= 4 %}
				                <li>
					                <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
                                    <a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
					                <div class="prize">¥ {{ goods.shop_price }}</div>
				                </li>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
			</ul>
		</div>
	</div>

    {% endfor %}
{% endblock %}

{% block bot_js %}
    <script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

fresh_shop/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">

					<form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">{{ errors.username }}, {{ msg1 }} </div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">{{ errors.pwd }} {{ msg2 }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
                            <h5 style="color: red">
                                  {{ msg3 }}
                            </h5>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

fresh_shop/templates/place_order.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-提交订单
{% endblock %}


{% block content %}
    <h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% if user.useraddress_set %}
                {% for addr in user.useraddress_set.all %}
                    <dd><input type="radio" name="address" checked="">{{ addr.address }} （{{ addr.signer_name }} 收） {{ addr.signer_name }}</dd>
                {% endfor %}
            {% endif %}
		</dl>
		<a href="{% url 'user:user_center_site' %}" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for cart in carts %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="/media/{{ cart.goods.goods_front_image }}"></li>
			<li class="col03">{{ cart.goods.name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ cart.goods.shop_price }}元</li>
			<li class="col06">{{ cart.nums }}</li>
			<li class="col07">{{ cart.total_price }}</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ carts.count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>6元</b></div>
			<div class="total_pay">实付款：<b>元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:void(0);" id="order_btn">提交订单</a>
	</div>
{% endblock %}

{% block bot_js %}
<script type="text/javascript" src="/static/js/jquery-1.12.2.js"></script>
{#	<script type="text/javascript">#}
{#		$('#order_btn').click(function() {#}
{#			localStorage.setItem('order_finish',2);#}
{##}
{#			$('.popup_con').fadeIn('fast', function() {#}
{##}
{#				setTimeout(function(){#}
{#					$('.popup_con').fadeOut('fast',function(){#}
{#						window.location.href = 'index.html';#}
{#					});#}
{#				},3000)#}
{##}
{#			});#}
{#		});#}
{#	</script>#}
    <script>
        $('#order_btn').click(function () {
            var check = $("input[name='address']").attr('checked')
            if (check == 'checked'){
                $.ajax({
                    url:'/order/add_order/',
                    type:'GET',
                    dataType:'json',
                    success: function (data) {
                        alert(data.msg)
                        window.location.reload()
                    },
                    error: function (data) {
                        alert(data.msg)
                    }

                })
            }else{
                $('#order_btn').href('/user/user_center_site/')
            }
            }
        )
    </script>
{% endblock %}

fresh_shop/templates/user_center_info.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block content %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>{{ user.phone }}</li>
							<li><span>联系地址：</span>{{ user.useraddress_set.first.address }}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_order.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock %}
{% block js %}
    <script type="text/javascript" src="/static/js/jquery-1.12.2.js"></script>
    <script>
    $(function () {

        {% for order in orders %}
            var total_price = 0;
            {% for ogoods in order.goods.all %}

                var shop_price = parseFloat($('#price{{ ogoods.id }}').html());
                var num = parseInt($('#num{{ ogoods.id }}').html());
                var s_price = num * shop_price;
                $('#sprice{{ ogoods.id }}').html(s_price+'元');
                total_price += s_price;

            {% endfor %}
            $('#tprice{{ order.id }}').html(total_price+ '元');
        {% endfor %}


    });
    </script>
{% endblock %}

{% block content %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.add_time }}</li>
					<li class="col02">订单号：{{ order.order_sn }}</li>
					<li class="col02 stress">未支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for ogoods in order.goods.all %}

								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/media/{{ ogoods.goods.goods_front_image }}"></li>
									<li class="col02">{{ ogoods.goods.name }}<em id="price{{ ogoods.id }}">{{ ogoods.goods.shop_price }}元/500g</em></li>
									<li class="col03" id="num{{ ogoods.id }}">{{ ogoods.goods_nums}}</li>
									<li class="col04" id="sprice{{ ogoods.id }}"></li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%" id="tprice{{ order.id }}">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
                {% endfor %}


				<div class="pagenation">
                    {% if orders.has_previous %}
					<a href="{% url 'user:user_center_order' %}?page={{ orders.previous_page_number }}">上一页</a>
                    {% endif %}

                    {% for i in orders.paginator.page_range  %}
                        {% ifequal i page %}
					        <a href="{% url 'user:user_center_order' %}?page={{ i }}" class="active">{{ i }}</a>
                        {% else %}
                            <a href="{% url 'user:user_center_order' %}?page={{ i }}">{{ i }}</a>
                        {% endifequal %}

                    {% endfor %}

                    {% if orders.has_next %}
					<a href="{% url 'user:user_center_order' %}?page={{ orders.next_page_number }}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_site.html
{% extends 'base_main.html' %}
{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block content %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user_addr.address }} （{{ user_addr.signer_name }} 收） {{ user_addr.signer_mobile }}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="addressee">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="detailed_address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock %}